//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapPlanComparison.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZapPlanComparison.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI.
        /// </summary>
        internal static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI.
        /// </summary>
        internal static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose [cGy].
        /// </summary>
        internal static string GraphicsDose {
            get {
                return ResourceManager.GetString("GraphicsDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphicsVolume.
        /// </summary>
        internal static string GraphicsVolume {
            get {
                return ResourceManager.GetString("GraphicsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices.
        /// </summary>
        internal static string Indices {
            get {
                return ResourceManager.GetString("Indices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max [cGy].
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean [cGy].
        /// </summary>
        internal static string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min [cGy].
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nCI.
        /// </summary>
        internal static string nCI {
            get {
                return ResourceManager.GetString("nCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of beams.
        /// </summary>
        internal static string NumOfBeams {
            get {
                return ResourceManager.GetString("NumOfBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of fractions.
        /// </summary>
        internal static string NumOfFractions {
            get {
                return ResourceManager.GetString("NumOfFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of isocenters.
        /// </summary>
        internal static string NumOfIsocenters {
            get {
                return ResourceManager.GetString("NumOfIsocenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physicist.
        /// </summary>
        internal static string PhysicistShort {
            get {
                return ResourceManager.GetString("PhysicistShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plannames.
        /// </summary>
        internal static string Plannames {
            get {
                return ResourceManager.GetString("Plannames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed dose [cGy].
        /// </summary>
        internal static string PrescribedDose {
            get {
                return ResourceManager.GetString("PrescribedDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed isodose.
        /// </summary>
        internal static string PrescribedIsodose {
            get {
                return ResourceManager.GetString("PrescribedIsodose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        internal static string Structures {
            get {
                return ResourceManager.GetString("Structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total MUs.
        /// </summary>
        internal static string TotalMU {
            get {
                return ResourceManager.GetString("TotalMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume [cm³].
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
